name: Deploy Go App to Docker on VPS

on:
  push:
    branches:
      - main  # atau branch lain yang ingin dipantau

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # Agar GitHub Actions bisa mengakses kode

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
      # Menggunakan private key SSH yang ada di Secrets

    - name: Deploy to VPS
      run: |
        # SSH ke VPS dan lakukan pull repo serta build Docker image
        # Login ke VPS dan pull image terbaru
        ssh -o StrictHostKeyChecking=no marzotadwi@103.187.147.156 "
          cd ~ && \
          git clone https://github.com/emdeweier/addons-receipt.git && \
          cd repo && \
          docker build -t addons-receipt . && \
          docker stop addons-receipt || true && \
          docker rm addons-receipt || true && \
          docker run -d -p 8080:8080 --name addons-receipt addons-receipt
        "
